### ISSUE TITLE
Mantaining state of the interface

### ISSUE THREAD

**Issue by francescodelduchetto** [laurencejbelliott/roswebcomponents#7]
I did not quite understand how is the state of the interface kept and what is the role of `rwc-receiver.js` in it. Can you please explain?

**Comment by francescodelduchetto** [comment]
Should it be used on client devices, as opposed to the main device interface (the robot touchscreen) which instead uses `rwc.js`?

**Comment by lozelliott** [comment]
`rwc-receiver.js` and its use will obviously be documented when it is more complete, but yes, it should be used on a blank HTML page on a secondary client device, and it will load the content of the current page of the main interface on the primary client, and mirror the state of the interface using topics such e.g.
```
/rwc/components_currently_clicked
/rwc/current_page
/rwc/disabled_components
```
and the ROS parameter `/interface_enabled`.
[test-alt.html](https://github.com/laurencejbelliott/roswebcomponents/blob/master/test-alt.html) serves as an example of its use.
